# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

remote_theme             : mmistakes/minimal-mistakes@4.16.3
minimal_mistakes_skin    : "mint"
# Site Settings
locale                   : "en-US"
title                    : "CHORDS Portal"
title_separator          : "-"
name                     : "EarthCubes"
description              : "Cloud Hosted Online Realtime Data"
url                      : https://earthcubeprojects-chords.github.io/chords-docs/ #If you change sites or github repos change this to match. It connects all across the website
baseurl                  : "chords-docs/" # the subpath of your site, e.g. "/chords"
downloadurl              : https://raw.githubusercontent.com #starting piece of the link for users to curl CHORDS
downloadbaseurl          : /NCAR/chords/master/chords_control #setting the path for users to download chords_control in the event of a repo change adjust this accordingly as it connects across the website.
repository               : # GitHub username/repo-name e.g. "NCAR/chords"
teaser                   : #"assets/images/banner_02.jpg"
logo                     : "/assets/images/chords_logo_text.png"
masthead_title           : " " #if you want to type something next to the logo you type it here. Otherwise " "
breadcrumbs              : true #disabled by default
words_per_minute         : 200
# comments:
#   provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2", "utterances", "custom"
#   disqus:
#     shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
#   discourse:
#     server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
#   facebook:                # https://developers.facebook.com/docs/plugins/comments
#     appid                :
#     num_posts            : # 5 (default)
#     colorscheme          : # "light" (default), "dark"
#   utterances:
#     theme                : # "github-light" (default), "github-dark"
#     issue_term           : # "pathname" (default)
# staticman:
#   allowedFields          : # ['name', 'email', 'url', 'message']
#   branch                 : # "master"
#   commitMessage          : # "New comment by {fields.name}"
#   filename               : # comment-{@timestamp}
#   format                 : # "yml"
#   moderation             : # true
#   path                   : # "/_data/comments/{options.slug}" (default)
#   requiredFields         : # ['name', 'email', 'message']
#   transforms:
#     email                : # "md5"
#   generatedFields:
#     date:
#       type               : # "date"
#       options:
#         format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
#   endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
# reCaptcha:
#   siteKey                :
#   secret                 :
atom_feed:
  path                   : " " # blank (default) uses feed.xml
search                   : false #search bar only searches for posts NOT pages.
#search_full_content      : true # Searches for posts only
# search_provider          : # lunr (default), algolia, google
# algolia:
#   application_id         : # YOUR_APPLICATION_ID
#   index_name             : # YOUR_INDEX_NAME
#   search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
#   powered_by             : # true (default), false
# google:
#   search_engine_id       : # YOUR_SEARCH_ENGINE_ID
#   instant_search         : # false (default), true
# # SEO Related
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :
# naver_site_verification  :
# Social Sharing
# twitter:
#   username               :
# facebook:
#   username               :
#   app_id                 :
#   publisher              :
# og_image                 : # Open Graph/Twitter default site image
# # For specifying social profiles
# # - https://developers.google.com/structured-data/customize/social-profiles
# social:
#   type                   : # Person or Organization (defaults to Person)
#   name                   : # If the user or organization name differs from the site's name
#   links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Sharing is Caring!"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "CHORDS"
  location         : "EarthCubes"
  email            : "chords@ucar.edu"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/NSFearthcube/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NCAR/chords"

      # Not sure if chords has twitter or instagram

    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   # url: "https://instagram.com/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   # url: "https://twitter.com/"

# Site Footer
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/NSFearthcube"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NCAR/chords"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "chords@ucar.edu"

    #   # Not sure if chords has twitter or instagram
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   # url:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   # url:

#Robyn testing      
defaults:
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single



# _portfolio 
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

        

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
      #include: ["_pages"]
    values:
      layout: single
      author_profile: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: true
      comments: false
      sidebar:
        nav: "docs"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      sidebar: true
      read_time: true
      comments: true
      share: true
      related: true
      
# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown #creates the table of contents menu. 
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# # Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
